volumes:
    db:
        driver: local

services:
    db:
        image: mysql:8.0
        restart: unless-stopped
        ports:
            - "3306:3306"
        command: mysqld --character-set-server=utf8mb4
        volumes:
            - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
            - db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123456
        healthcheck:
            test: "mysql -u root -p$$MYSQL_ROOT_PASSWORD -e 'USE microstamp;'"
            interval: 60s
            retries: 5
            start_period: 30s
        networks:
            - main

    service-registry:
        build:
            context: ./microstamp-service-registry
        ports:
            - "8002:8002"
        depends_on:
            db:
                condition: service_healthy
        healthcheck:
            test: "curl -f http://service-registry:8002"
            interval: 5s
            retries: 5
            start_period: 3s
        networks:
            - main

    api-gateway:
        build:
            context: ./microstamp-api-gateway
        ports:
            - "8000:8000"
        depends_on:
            service-registry:
                condition: service_healthy
        healthcheck:
            test: "curl -f http://api-gateway:8000/actuator/health"
            interval: 5s
            retries: 5
            start_period: 3s
        environment:
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8002/eureka
            - ALLOWED_ORIGINS=http://127.0.0.1:3000
        networks:
            - main

    authorization-server:
        build:
            context: ./microstamp-authorization-server
        ports:
            - "8001:8001"
        depends_on:
            service-registry:
                condition: service_healthy
        healthcheck:
            test: "curl -f http://authorization-server:8001/login"
            interval: 5s
            retries: 5
            start_period: 3s
        environment:
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8002/eureka
            - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/microstamp
            - CORS_WHITELIST=http://api-gateway:8000,http://127.0.0.1:3000
            - SECURITY_ISSUER-URI=http://authorization-server:8001
        networks:
            - main

    step1:
        build:
            context: ./microstamp-step1
        ports:
            - "8101:8101"
        depends_on:
            service-registry:
                condition: service_healthy
        healthcheck:
            test: "curl -f -s -w '%{http_code}%' http://step1:8101 | grep -q '401'"
            interval: 5s
            retries: 5
            start_period: 3s
        environment:
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8002/eureka
            - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/step1
            - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://authorization-server:8001
            - CORS_WHITELIST=http://api-gateway:8000,http://127.0.0.1:3000
        networks:
            - main

    step2:
        build:
            context: ./microstamp-step2
        ports:
            - "8102:8102"
        depends_on:
            service-registry:
                condition: service_healthy
        healthcheck:
            test: "curl -f -s -w '%{http_code}%' http://step2:8102 | grep -q '401'"
            interval: 5s
            retries: 5
            start_period: 3s
        environment:
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8002/eureka
            - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/step2
            - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://authorization-server:8001
            - CORS_WHITELIST=http://api-gateway:8000,http://127.0.0.1:3000
        networks:
            - main

    step3:
        build:
            context: ./microstamp-step3
        ports:
            - "8103:8103"
        depends_on:
            service-registry:
                condition: service_healthy
        healthcheck:
            test: "curl -f -s -w '%{http_code}%' http://step3:8103 | grep -q '401'"
            interval: 5s
            retries: 5
            start_period: 3s
        environment:
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8002/eureka
            - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/step3
            - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://authorization-server:8001
            - CORS_WHITELIST=http://api-gateway:8000,http://127.0.0.1:3000
        networks:
            - main

    step4:
        build:
            context: ./microstamp-step4
        ports:
            - "8104:8104"
        depends_on:
            service-registry:
                condition: service_healthy
        healthcheck:
            test: "curl -f -s -w '%{http_code}%' http://step4:8104 | grep -q '401'"
            interval: 5s
            retries: 5
            start_period: 3s
        environment:
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8002/eureka
            - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/step4
            - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://authorization-server:8001
            - CORS_WHITELIST=http://api-gateway:8000,http://127.0.0.1:3000
        networks:
            - main

    step4-new:
        build:
            context: ./microstamp-step4-new
        ports:
            - "8105:8105"
        depends_on:
            service-registry:
                condition: service_healthy
        healthcheck:
            test: "curl -f -s -w '%{http_code}%' http://step4-new:8105 | grep -q '401'"
            interval: 5s
            retries: 5
            start_period: 3s
        environment:
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8002/eureka
            - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/step4-new
            - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://authorization-server:8001
            - CORS_WHITELIST=http://api-gateway:8000,http://127.0.0.1:3000
        networks:
            - main

    ui:
        build:
            context: ./microstamp-ui
            args:
                - VITE_UI_URL=http://127.0.0.1:3000
                - VITE_GATEWAY_URL=http://127.0.0.1:8000
                - VITE_AUTH_URL=http://127.0.0.1:8001
                - VITE_TOKEN_AUTH_URL=http://localhost:8001
                - VITE_AUTH_CLIENT_ID=fbefbe1f-933d-4012-b730-16db007cd13e
                - VITE_AUTH_CLIENT_SECRET=bdbdc73c-63c6-4aac-8634-bfbafa0417b0
        ports:
            - "3000:80"
        networks:
            - main
networks:
    main:
        driver: bridge
