volumes:
  db:
    driver: local

services:
  db:
    image: mysql:8.4
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    command: mysqld --mysql-native-password=ON --character-set-server=utf8mb4
    volumes:
      - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - microstamp-network
  microstamp-service-registry:
    image: gabrielfrancelino/microstamp-service-registry:0.0.1-SNAPSHOT
    container_name: microstamp-service-registry
    ports:
      - "8761:8761"
    networks:
      - microstamp-network
  microstamp-api-gateway:
    image: gabrielfrancelino/microstamp-api-gateway:0.0.1-SNAPSHOT
    container_name: microstamp-api-gateway
    ports:
      - "9191:9191"
    depends_on:
      - microstamp-service-registry
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://microstamp-service-registry:8761/eureka/
      - ALLOWED_ORIGINS=http="//authorization-server:9000/,http://microstamp-step1:8091/,http://microstamp-step2:8090/,http://microstamp-step3:8080/,http://microstamp-service-registry:8761/,http://127.0.0.1:5173/"
    networks:
      - microstamp-network
  microstamp-authorization-server:
    image: gabrielfrancelino/microstamp-authorization-server:0.0.1-SNAPSHOT
    container_name: microstamp-authorization-server
    restart: unless-stopped
    ports:
      - "9000:9000"
    depends_on:
      - microstamp-service-registry
      - db
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://microstamp-service-registry:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/microstamp?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.3&allowPublicKeyRetrieval=true
      - SPRING_FLYWAY_URL=jdbc:mysql://db:3306/microstamp?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.3&allowPublicKeyRetrieval=true
    networks:
      - microstamp-network
  microstamp-step1:
    image: gabrielfrancelino/microstamp-step1-microservice:1.0.0
    container_name: microstamp-step1
    restart: unless-stopped
    ports:
      - "8091:8091"
    depends_on:
      - microstamp-service-registry
      - db
    environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://microstamp-service-registry:8761/eureka/
        - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/step1?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.3&allowPublicKeyRetrieval=true
        - SPRING_FLYWAY_URL=jdbc:mysql://db:3306/step1?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.3&allowPublicKeyRetrieval=true
        - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://microstamp-authorization-server:9000
    networks:
      - microstamp-network
  microstamp-step2:
    image: gabrielfrancelino/microstamp-step2-microservice:1.0.0
    container_name: microstamp-step2
    restart: unless-stopped
    ports:
      - "8090:8090"
    depends_on:
      - microstamp-service-registry
      - db
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://microstamp-service-registry:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/step2?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.3&allowPublicKeyRetrieval=true
      - SPRING_FLYWAY_URL=jdbc:mysql://db:3306/step2?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.3&allowPublicKeyRetrieval=true
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://microstamp-authorization-server:9000
    networks:
      - microstamp-network
  microstamp-step3:
    image: gabrielfrancelino/microstamp-step3:0.0.1-SNAPSHOT
    container_name: microstamp-step3
    restart: unless-stopped
    ports:
      - "8090:8090"
    depends_on:
      - microstamp-service-registry
      - db
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://microstamp-service-registry:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/step3?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.3&allowPublicKeyRetrieval=true
      - SPRING_FLYWAY_URL=jdbc:mysql://db:3306/step3?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.3&allowPublicKeyRetrieval=true
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://microstamp-authorization-server:9000
    networks:
      - microstamp-network
networks:
  microstamp-network:
    driver: bridge