package microstamp.cast.step4.entity.enums;


public enum SystemicFactorCategory {
    COMMUNICATION_AND_COORDINATION,
    SAFETY_INFORMATION_SYSTEM,
    SAFETY_MANAGEMENT_SYSTEM_DESIGN,
    SAFETY_CULTURE,
    CHANGES_AND_DYNAMICS_OVER_TIME,
    ECONOMIC_AND_ENVIRONMENTAL_FACTORS
}
